language: node_js
node_js:
  - 'stable'
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test' -U postgres
  - npm install
  - npm install nyc -g
  - npm run db:migrate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: npm run coverage
after_script:
  - ./cc-test-reporter after-build -t lcov --exit-code $TRAVIS_TEST_RESULT